In [1]:
# Data load 

import pandas as pd 
df = pd.read_csv("sales_raw_new_2026.csv")

In [2]:
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [3]:
# duplicates remove

df = df.drop_duplicates()

In [4]:
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost
0        2001  2026-01-21     Neha   West   Laptop  16494  13135
1        2002  2026-01-07   Anjali  North  Monitor  35140  19722
2        2003  2026-01-28    Vikas  North   Mobile  18889  13511
3        2004  2026-01-04    Kiran  North   Mobile  89657  66187
4        2005  2026-03-02    Rahul   West   Laptop  35977  20290
..        ...         ...      ...    ...      ...    ...    ...
195      2196  2026-01-26    Kiran   East  Printer  28305  16671
196      2197  2026-01-04   Suresh  South  Printer  18669  13476
197      2198  2026-03-01   Anjali  South   Mobile  52605  33403
198      2199  2026-02-03     Neha  North   Laptop  57296  39944
199      2200  2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [5]:
#fix date column 

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [6]:
df = df.dropna(subset=['Order_Date'])

In [7]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        2001 2026-01-21     Neha   West   Laptop  16494  13135
1        2002 2026-01-07   Anjali  North  Monitor  35140  19722
2        2003 2026-01-28    Vikas  North   Mobile  18889  13511
3        2004 2026-01-04    Kiran  North   Mobile  89657  66187
4        2005 2026-03-02    Rahul   West   Laptop  35977  20290
..        ...        ...      ...    ...      ...    ...    ...
195      2196 2026-01-26    Kiran   East  Printer  28305  16671
196      2197 2026-01-04   Suresh  South  Printer  18669  13476
197      2198 2026-03-01   Anjali  South   Mobile  52605  33403
198      2199 2026-02-03     Neha  North   Laptop  57296  39944
199      2200 2026-02-21    Priya   East   Mobile  12701  10702

[200 rows x 7 columns]

In [8]:
df['Profit']= df['Sales']-df['Cost']
df['Year']= df['Order_Date'].dt.year
df['Month']= df['Order_Date'].dt.month

In [9]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2

In [11]:
#data python + sql + excel

In [10]:
import pandas as pd
from sqlalchemy import create_engine

In [11]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,2001,2026-01-21,Neha,West,Laptop,16494,13135,3359,2026,1
1,2002,2026-01-07,Anjali,North,Monitor,35140,19722,15418,2026,1
2,2003,2026-01-28,Vikas,North,Mobile,18889,13511,5378,2026,1
3,2004,2026-01-04,Kiran,North,Mobile,89657,66187,23470,2026,1
4,2005,2026-03-02,Rahul,West,Laptop,35977,20290,15687,2026,3
...,...,...,...,...,...,...,...,...,...,...
195,2196,2026-01-26,Kiran,East,Printer,28305,16671,11634,2026,1
196,2197,2026-01-04,Suresh,South,Printer,18669,13476,5193,2026,1
197,2198,2026-03-01,Anjali,South,Mobile,52605,33403,19202,2026,3
198,2199,2026-02-03,Neha,North,Laptop,57296,39944,17352,2026,2
199,2200,2026-02-21,Priya,East,Mobile,12701,10702,1999,2026,2

In [15]:
from sqlalchemy import create_engine

# Now create the engine
engine = create_engine('mysql+pymysql://root:root123@localhost:3306/salesdb')

In [16]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [12]:
import pymysql

# Connect directly to your local MySQL server
conn = pymysql.connect(host='localhost', port=3306, user='root', password='root123')
cursor = conn.cursor()

# Command to physically create the database inside MySQL
cursor.execute("CREATE DATABASE IF NOT EXISTS salesdb;")
print("Database 'salesdb' created successfully! 🚀")

# Close connection
cursor.close()
conn.close()

Database 'salesdb' created successfully! 🚀

In [16]:
df.to_sql(name='sales_data',con=engine,if_exists='append',index= False)

200